spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        generate_statistics: true
        cache:
          use_minimal_puts: true
          use_second_level_cache: true
          use_query_cache: true
          missing_cache_strategy: create
          region:
            factory_class: infinispan
          infinispan:
            entity:
              cfg: replicated-entity
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE

logging:
  level:
    org.hibernate.cache: DEBUG
#    org.jgroups: TRACE
